### ISSUE TITLE
Color / formatting codes are not working on the scoreboard

### ISSUE THREAD

**Issue by k-jiang** [ShieldCommunity/SternalBoard#72]
Color code / formatting code are not working on the scoreboard.

Tested with
- SternalBoard-2.3.0-all.jar
- PaperSpigot 1.20.6
- PlaceholderAPI 2.11.6

```yaml
settings:
  animated: false
  mode: NORMAL
  scoreboard-interval-update: 20
  scoreboard:
    title: '&b&lSternal&f&lBoard &d&lWORLD'
    lines:
       - '&eShield&6Community &7| &aTest server'
```

**Screenshots**
<img width="294" alt="image" src="https://github.com/ShieldCommunity/SternalBoard/assets/6910542/6d13d912-b2c4-4851-9e66-68d1cae5db29">

**Comment by k-jiang** [comment]
MiniMessage formatting does not work either.

**Comment by xism4** [comment]
> MiniMessage formatting does not work either.
> 
> ```yaml
> settings:
>   animated: false
>   mode: NORMAL
>   scoreboard-interval-update: 20
>   scoreboard:
>     title: '&b&lSternal&f&lBoard &d&lWORLD'
>     lines:
>        - '&eShield&6Community &7| &aTest server'
>        - '<color:#87CEFA><b><st>*=--=--=--=--=*</st></b></color>'
> ```
> 
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/6910542/341626328-22f3213b-88f9-49d3-850b-c4e9f1f390bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTk5OTIsIm5iZiI6MTcxODk1OTY5MiwicGF0aCI6Ii82OTEwNTQyLzM0MTYyNjMyOC0yMmYzMjEzYi04OGY5LTQ5ZDMtODUwYi1jNGU5ZjFmMzkwYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDg0ODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEyNDhmZDFkMWVkOTA5MmI1ZjMyMzBiYWU1OGVhM2ZhZTY4NTY5ZTEzMTkzNDUzZDZmMTZiZDViYzFlYjM2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m3JyZYIVTzZBeaLWC6n6q4zTGH8DV1SS0Lc4JGbzo3w">

Try with the format<red>hello

**Comment by k-jiang** [comment]
> > MiniMessage formatting does not work either.
> > ```yaml
> > settings:
> >   animated: false
> >   mode: NORMAL
> >   scoreboard-interval-update: 20
> >   scoreboard:
> >     title: '&b&lSternal&f&lBoard &d&lWORLD'
> >     lines:
> >        - '&eShield&6Community &7| &aTest server'
> >        - '<color:#87CEFA><b><st>*=--=--=--=--=*</st></b></color>'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/6910542/341626328-22f3213b-88f9-49d3-850b-c4e9f1f390bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTk5OTIsIm5iZiI6MTcxODk1OTY5MiwicGF0aCI6Ii82OTEwNTQyLzM0MTYyNjMyOC0yMmYzMjEzYi04OGY5LTQ5ZDMtODUwYi1jNGU5ZjFmMzkwYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDg0ODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEyNDhmZDFkMWVkOTA5MmI1ZjMyMzBiYWU1OGVhM2ZhZTY4NTY5ZTEzMTkzNDUzZDZmMTZiZDViYzFlYjM2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m3JyZYIVTzZBeaLWC6n6q4zTGH8DV1SS0Lc4JGbzo3w">
> 
> Try instead with the default MiniMessage colours (<> and the name

No, not working
![Screenshot from 2024-06-23 18-57-18](https://github.com/ShieldCommunity/SternalBoard/assets/6910542/c1ccf5d5-25b8-4461-82bc-d32ccc28b279)
```yaml
settings:
  animated: false
  mode: NORMAL
  scoreboard-interval-update: 20
  scoreboard:
    title: 'World'
    lines:
       - '<red>*=--=--=--=--=*</red>'
```
